function k(b,a,c,d){b.v.gb(b.lb,a,c,d)}function l(b,a,c,d){b.v.ca?k(b,a,c,d):b.v.Ce()._OnMessageFromDOM({type:"event",component:b.lb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.v.C(b.lb,a,c)}function aa(b,a){for(const [c,d]of a)q(b,c,d)}function t(b){b.Rb||(b.v.md(b.Ud),b.Rb=!0)}window.Fb=class{constructor(b,a){this.v=b;this.lb=a;this.Rb=!1;this.Ud=()=>this.Ka()}cd(){}Ka(){}};
window.lf=class{constructor(){this.Zc=-1}j(){-1!==this.Zc&&(self.clearTimeout(this.Zc),this.Zc=-1)}};"use strict";class ba{constructor(b){this.Gc=b;this.Jc=!1;this.Qc=!0}}function ca(b,a){const c=a.elementId,d=b.gd(c,a),e=new ba(d);b.ob.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Qc=!!a.isVisible;d.addEventListener("focus",()=>{u(b,"elem-focused",c)});d.addEventListener("blur",()=>{u(b,"elem-blurred",c)});b.Nb&&document.body.appendChild(d)}
function da(b,a,c){q(b,a,d=>{const e=v(b,d.elementId);return c(e,d)})}function v(b,a){b=b.ob.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Gc}function u(b,a,c,d){d||(d={});d.elementId=c;k(b,a,d)}function ea(b,a,c){var d;d||(d={});d.elementId=c;l(b,a,d)}
window.ne=class extends self.Fb{constructor(b){super(b,"text-input");this.ob=new Map;this.Nb=!0;aa(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const c=v(this,a);this.Nb&&c.parentElement.removeChild(c);this.ob.delete(a)}],["set-visible",a=>{if(this.Nb){var c=this.ob.get(a.elementId),d=c.Gc;c.Jc?d.style.display=a.isVisible?"":"none":c.Qc=!!a.isVisible}}],["update-position",a=>{if(this.Nb){var c=this.ob.get(a.elementId),d=c.Gc;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Jc||(c.Jc=!0,c.Qc&&(d.style.display=""))}}],["update-state",a=>{const c=v(this,a.elementId);this.uc(c,a)}],["focus",a=>{const c=v(this,a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=v(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{v(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{v(this,a.elementId).removeAttribute(a.name)}]]);
da(this,"get-element",a=>a)}gd(){throw Error("required override");}uc(){throw Error("required override");}};"use strict";const fa=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent),ha=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ia=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.af?new Promise(c=>{const d="c3_resolve_"+ia;++ia;self[d]=c;a.textContent=b.ef+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ja=!1,ka=!1;function la(){if(!ja){try{new Worker("blob://",{get type(){ka=!0}})}catch(b){}ja=!0}return ka}let z=new Audio;
const oa={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function pa(b){b=await qa(b);return(new TextDecoder("utf-8")).decode(b)}
function qa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,ra=new Map;let sa=0;const ta=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ta.push(b)};const ua=new Set(["cordova","playable-ad","instant-games"]);let va=!1;
window.hb=class b{constructor(a){this.ca=a.gf;this.wa=null;this.ba="";this.Xa=a.df;this.Cb={};this.Qa=this.ua=null;this.Pb=[];this.J=this.na=null;this.Nc=!1;this.Bd=0;this.rb=null;this.Wa=-1;this.Xe=()=>this.Ke();this.Va=[];this.$c=null;this.Vd=[];this.A=a.Wd;this.Sb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&la()||(this.ca=!1);this.ca&&ha&&(this.ca=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ca=!1;if("cordova"===
this.A&&this.ca)if(w){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.eb()?self.chrome.webview.addEventListener("message",c=>this.rd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.rd(c));this.Vb=this.ra=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");
this.C("runtime","cordova-fetch-local-file",c=>this.Ge(c));this.C("runtime","create-job-worker",()=>this.He());this.C("runtime","send-wrapper-extension-message",c=>this.Ne(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.pd(a)):this.pd(a)}j(){this.vc();this.wa&&(this.wa=this.wa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Qa&&(this.Qa.j(),this.Qa=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}re(){return fa&&"cordova"===this.A}qc(){const a=
navigator.userAgent;return fa&&ua.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}pe(){return w}jd(){return w&&ua.has(this.A)}eb(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async pd(a){"macos-wkwebview"===this.A?this.ib({type:"ready"}):this.eb()&&(this.Qe(),this.Vd=(await this.Fe()).registeredComponentIds);if("playable-ad"===this.A){this.ra=self.c3_base64files;this.Vb={};await this.ye();
for(let d=0,e=a.Za.length;d<e;++d){var c=a.Za[d];this.Vb.hasOwnProperty(c)?a.Za[d]={af:!0,ef:this.Vb[c]}:this.ra.hasOwnProperty(c)&&(a.Za[d]=URL.createObjectURL(this.ra[c]))}a.jc=[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.md(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.cf?this.ba=a.cf:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.jf&&(this.Cb=a.jf);
c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Je(d));this.rb=new self.se(this);await wa(this.rb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ca?await this.Ee(a,c.port2):
await this.De(a,c.port2)}xc(a){a=this.Cb.hasOwnProperty(a)?this.Cb[a]:a.endsWith("/workermain.js")&&this.Cb.hasOwnProperty("workermain.js")?this.Cb["workermain.js"]:"playable-ad"===this.A&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async lc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Sb)return a=await this.Eb(d.$e?a:this.Xa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=
new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}pa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}od(a){var c=this.ba,d=location.href,e=this.pa(),f=this.ia(),g=window.devicePixelRatio,h=b.cb(),m=a.pf,n=window.cr_previewImageBlobs||this.ra,p=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.cr_swClientId||
"";a=a.Wd;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.rb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.nf,jobScheduler:{inputPort:B.Mc,outputPort:B.Uc,maxNumWorkers:B.Ue},supportedAudioFormats:oa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Xa+"opus.wasm.wasm",isFileProtocol:this.Sb,isiOSCordova:this.re(),isiOSWebView:this.qc(),isWebView2Wrapper:this.eb(),wrapperComponentIds:this.Vd,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ee(a,c){const d=this.xc(a.hf);"preview"===this.A?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const n=p=>{this.ua.removeEventListener("message",n);p.data&&"ok"===p.data.type?h():m()};this.ua.addEventListener("message",n);this.ua.postMessage({type:"construct-worker-init",
"import":(new URL(d,this.ba)).toString()})})):this.ua=await this.lc(d,this.ba,{type:"module",name:"Runtime",$e:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.jc||[],g=a.Za;f=await Promise.all(f.map(h=>this.La(h)));g=await Promise.all(g.map(h=>this.La(h)));if("cordova"===this.A)for(let h=0,m=a.ic.length;h<
m;++h){const n=a.ic[h],p=n[0];if(p===a.ad||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))n[1]=await this.La(p)}this.ua.postMessage(Object.assign(this.od(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ic,mainProjectScript:a.ad,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...xa(this.rb)]);this.Pb=F.map(h=>new h(this));this.nd();ya(this.na);self.c3_callFunction=(h,m)=>{var n=this.na;return n.v.ld(n.lb,
"js-invoke-function",{name:h,params:m})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.gb("runtime","go-to-last-error-script"))}async De(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Pb=F.map(g=>new g(this));this.nd();var d=a.Za.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.jc)){var e=[...a.jc].map(g=>
g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.La(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;e=a.ad;const f=a.ic;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.La(h),await y(h),"preview"!==this.A||d[g]||this.sd(g,"main script did not run to completion")}catch(m){this.sd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.La(h),await y(h);"preview"===this.A&&"object"!==typeof self.kf.mf?
(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.od(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:ta}),ya(this.na),this.qd(),this.Qa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Qa,a))}sd(a,c){this.Kb();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}qd(){this.Kb()}Kb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async He(){const a=await za(this.rb);return{outputPort:a,transferables:[a]}}Ce(){if(this.ca)throw Error("not available in worker mode");return this.Qa}gb(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,
dispatchOpts:e||null,data:d,responseId:null},f)}ld(a,c,d,e,f){const g=sa++,h=new Promise((m,n)=>{ra.set(g,{resolve:m,reject:n})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ie(a);if("result"===c)this.Le(a);else if("runtime-ready"===c)this.Me();else if("alert-error"===c)this.Kb(),alert(a.message);else if("creating-runtime"===c)this.qd();else throw Error(`unknown message '${c}'`);
}Ie(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Jb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Jb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Jb(f,!1,""+h)}):this.Jb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Jb(a,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Le(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ra.get(c);d?e.resolve(a):e.reject(a);ra.delete(c)}C(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Db(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}nd(){for(const a of this.Pb)if("runtime"===a.lb){this.na=a;
return}throw Error("cannot find runtime DOM handler");}Je(a){this.gb("debugger","message",a)}Me(){for(const a of this.Pb)a.cd()}static cb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||va)}static td(a){va=!!a}md(a){this.Va.push(a);this.Cc()}Pe(a){a=this.Va.indexOf(a);if(-1===a)throw Error("invalid callback");this.Va.splice(a,1);this.Va.length||this.vc()}Cc(){-1===this.Wa&&this.Va.length&&(this.Wa=requestAnimationFrame(this.Xe))}vc(){-1!==this.Wa&&
(cancelAnimationFrame(this.Wa),this.Wa=-1)}Ke(){this.Wa=-1;for(const a of this.Va)a();this.Cc()}Ba(a){this.na.Ba(a)}Ja(a){this.na.Ja(a)}Bc(){this.na.Bc()}Ib(a){this.na.Ib(a)}qe(){return!!oa["audio/webm; codecs=opus"]}async Re(a){a=await this.ld("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}ue(a){this.Nc=!0;this.Bd=a}oe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}kd(a){return!this.oe(a)}async La(a){return"cordova"===this.A&&
(a.startsWith("file:")||this.Sb&&this.kd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Eb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ge(a){const c=a.filename;switch(a.as){case "text":return await this.me(c);case "buffer":return await this.Eb(c);default:throw Error("unsupported type");}}fd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async me(a){a=
await this.fd(a);return await pa(a)}wc(){if(C.length&&!(8<=E)){E++;var a=C.shift();this.ze(a.filename,a.ff,a.Ze)}}Eb(a){return new Promise((c,d)=>{C.push({filename:a,ff:e=>{E--;this.wc();c(e)},Ze:e=>{E--;this.wc();d(e)}});this.wc()})}async ze(a,c,d){try{const e=await this.fd(a),f=await qa(e);c(f)}catch(e){d(e)}}rd(a){if("entered-fullscreen"===a)b.td(!0),H(this.na);else if("exited-fullscreen"===a)b.td(!1),H(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.$c(a),
this.$c=null):"extension-message"===c?this.gb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Ne(a){this.ib({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}ib(a){this.eb()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Qe(){window.moveTo=(a,c)=>
{this.ib({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.ib({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Fe(){return this.eb()?new Promise(a=>{this.$c=a;this.ib({type:"wrapper-init"})}):Promise.resolve()}async ye(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.xe(c,d));await Promise.all(a)}async xe(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.Vb[a]=c.str;else{let d=
await this.Be(c);d||(d=this.Ae(c));this.ra[a]=d}}async Be(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ae(a){a=this.Oe(a);return this.we(a.data,a.bf)}Oe(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{bf:a,data:d}}we(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const I=self.hb;
function Aa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Ba=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ca={dispatchUserScriptEvent:!0},Da={dispatchRuntimeEvent:!0};
function Ea(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Fa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await Fa(b)}finally{URL.revokeObjectURL(b)}}
function Ga(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ha(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Ga(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Ia(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ja=new Set(["input","textarea","datalist","select"]),Ka=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ka.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function La(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ha(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ma=!1;document.addEventListener("pause",()=>Ma=!0);document.addEventListener("resume",()=>Ma=!1);function ya(b){b.Ad=!0;b.Rc=b.v.pa();b.sb=b.v.ia()}function H(b){if(!b.$){var a=I.cb();a&&"any"!==b.Xc&&Na(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ia()})}}async function Oa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Pa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Qa(b){return await self.C3_GetSvgImageSize(b.blob)}function Ra(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Sa(b){self.setTimeout(()=>{b.zd=!0},1E3);"cordova"===b.v.A?(document.addEventListener("pause",()=>Ta(b,!0)),document.addEventListener("resume",()=>Ta(b,!1))):document.addEventListener("visibilitychange",()=>Ta(b,"hidden"===document.visibilityState));b.Zb=!("hidden"!==document.visibilityState&&!Ma);return{isSuspended:b.Zb}}
function Ua(b){b.vd||(b.vd=!0,window.addEventListener("deviceorientation",a=>{b.$||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Va(b){b.ud||(b.ud=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Wa(b){await Ea(b.url)}
function Xa(b,a){b.Cd=a.message;-1===b.Hc&&(b.Hc=setTimeout(()=>{b.Hc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Cd)},250))}function Ya(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:I.cb(),innerWidth:b.pa(),innerHeight:b.ia()})}function Ta(b,a){b.Zb!==a&&((b.Zb=a)?b.v.vc():b.v.Cc(),k(b,"visibilitychange",{hidden:a}))}
function Za(b,a,c){"Backspace"===c.key&&L(c);if(!b.$){var d=Ba.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}function ab(b,a,c,d){b.$||Aa(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function bb(b){window!==window.top&&window.focus();cb(b.target)&&document.activeElement&&!cb(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.xb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),ab(b,d,c,Ca),b.xb=c.buttons)}}
function db(b,a,c){if(!b.$&&!Aa(c)){var d=b.xb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},J);b.xb=c.buttons;ab(b,c.type,c,Ca)}}
function N(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
J)}}function eb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function fb(b,a,c,d){const e=b.pa(),f=b.ia();b.Ya=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.cb()}):10>d&&gb(b,e,f,d+1)}
function gb(b,a,c,d){-1!==b.Ya&&clearTimeout(b.Ya);b.Ya=setTimeout(()=>fb(b,a,c,d),48)}
function Na(b){b=b.Xc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function cb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.Db(class extends self.Fb{constructor(b){super(b,"runtime");this.Hd=!0;this.Ad=!1;this.Ya=-1;this.Xc="any";this.Zb=this.ud=this.vd=!1;this.ec=document.createElement("div");this.ec.className="c3-screen-reader-text";this.ec.setAttribute("aria-live","polite");document.body.appendChild(this.ec);this.Ea=null;this.$=!1;this.Cd="";this.Hc=-1;this.zd=!1;this.Rc=b.pa();this.sb=b.ia();this.da=this.Bb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Nc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=
d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Hd&&(e.style.display="",this.Hd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Oa(d));b.C("runtime","raster-svg-image",d=>Pa(d));b.C("runtime",
"get-svg-image-size",d=>Qa(d));b.C("runtime","set-target-orientation",d=>{this.Xc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ra(d));b.C("runtime","go-to-script",d=>Ra(d));b.C("runtime","before-start-ticking",()=>Sa(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ea||(this.Ea=document.createElement("div"),this.Ea.id="inspectOutline",document.body.appendChild(this.Ea));var e=this.Ea;e.style.display=
"";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ea&&(this.Ea.style.display="none")});b.C("runtime","enable-device-orientation",()=>Ua(this));b.C("runtime","enable-device-motion",()=>Va(this));b.C("runtime","add-stylesheet",d=>Wa(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ec.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.J.style.display="";this.v.ue(d.duration)});b.C("runtime","export-to-video-progress",d=>Xa(this,d));b.C("runtime","exported-to-video",d=>{window.Ye({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Ye({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ia(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",
L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.xb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",La,{passive:!1});window.addEventListener("wheel",La,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Ad){var d=this.pa();var e=this.ia();if(this.v.jd()){if(this.zd){if(this.Rc===
d&&e<this.sb){this.Bb=this.sb-e;eb(this,this.sb,this.Bb);d=void 0;break a}0<this.Bb&&(this.Bb=0,eb(this,e,this.Bb))}this.Rc=d;this.sb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.cb()});this.v.qc()&&(-1!==this.Ya&&clearTimeout(this.Ya),fb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>
H(this));window.addEventListener("fullscreenerror",d=>Ya(this,d));window.addEventListener("webkitfullscreenerror",d=>Ya(this,d));window.addEventListener("mozfullscreenerror",d=>Ya(this,d));if(b.qc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ia(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ra=new Set;this.Xb=new WeakSet;this.va=!1}cd(){window.addEventListener("focus",()=>{k(this,"window-focus",null,Da)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},Da);this.xb=0});window.addEventListener("focusin",a=>{a=a.target;(Ja.has(a.tagName.toLowerCase())||Ia(a))&&
k(this,"keyboard-blur",null,Da)});window.addEventListener("keydown",a=>Za(this,"keydown",a));window.addEventListener("keyup",a=>Za(this,"keyup",a));window.addEventListener("dblclick",a=>ab(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.$||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{bb(a);M(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{bb(a);db(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>db(this,
"pointermove",a)),window.addEventListener("mouseup",a=>db(this,"pointerup",a)),window.addEventListener("touchstart",a=>{bb(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.Bc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.pe()&&!this.v.jd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{eb(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}pa(){return this.v.pa()}ia(){return this.v.ia()}Bc(){var b=[...this.Ra];this.Ra.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.Xb.has(a)||this.Ra.add(a)})}Ba(b){if("function"!==typeof b.play)throw Error("missing play function");
this.Xb.delete(b);let a;try{a=b.play()}catch(c){this.Ra.add(b);return}a&&a.catch(()=>{this.Xb.has(b)||this.Ra.add(b)})}Ja(b){this.Ra.delete(b);this.Xb.add(b)}Ib(b){this.va=!!b}});"use strict";async function wa(b){if(b.Se)throw Error("already initialised");b.Se=!0;var a=b.xa.xc(("playable-ad"===b.xa.A?b.xa.Xa:"")+"dispatchworker.js");b.Fc=await b.xa.lc(a,b.kb,{name:"DispatchWorker"});a=new MessageChannel;b.Mc=a.port1;b.Fc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Uc=await za(b)}
function xa(b){return[b.Mc,b.Uc]}async function za(b){const a=b.Id.length;var c=b.xa.xc(("playable-ad"===b.xa.A?b.xa.Xa:"")+"jobworker.js");c=await b.xa.lc(c,b.kb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Fc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Id.push(c);return e.port1}
self.se=class{constructor(b){this.xa=b;this.kb=b.ba;this.kb="preview"===b.A?this.kb+"workers/":this.kb+b.Xa;this.Ue=Math.min(navigator.hardwareConcurrency||2,16);this.Fc=null;this.Id=[];this.Uc=this.Mc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.hb({gf:!0,hf:"workermain.js",Za:["scripts/c3runtime.js"],ic:[],ad:"",df:"scripts/",jc:[],Wd:"html5"}));"use strict";
async function ib(b,a){a=a.type;let c=!0;0===a?c=await jb():1===a&&(c=await kb());k(b,"permission-result",{type:a,result:c})}async function jb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function kb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.hb.Db(class extends self.Fb{constructor(b){super(b,"touch");q(this,"request-permission",a=>ib(this,a))}});"use strict";const lb=180/Math.PI;
async function mb(b,a){if(a.isiOSCordova||a.isSafari)b.ac=!0;b.Yc=a.timeScaleMode;b.Nd=["equalpower","HRTF","soundfield"][a.panningModel];b.yd=["linear","inverse","exponential"][a.distanceModel];b.Od=a.refDistance;b.Md=a.maxDistance;b.Qd=a.rolloffFactor;if(b.v.Nc)b.ac=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.Bd)});else{var c={latencyHint:a.latencyHint};b.Td||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");nb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&nb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Na=b.g.createGain();b.Na.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function ob(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,m=a.vol,n=a.pos,p=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Jd=g.slice(0);pb(b,g);try{b.R=await qb(b,c,d,e,g,f);if(p){P(b.R,!0);var r=b.R,B=p.innerAngle,ma=p.outerAngle,na=p.outerGain;if(r.qb){rb(r,p.x,p.y,p.z,p.angle);var D=self.$a.ve;r.sa[0]!==D(B)&&
(r.sa[0]=D(B),r.F.coneInnerAngle=D(B));r.sa[1]!==D(ma)&&(r.sa[1]=D(ma),r.F.coneOuterAngle=D(ma));r.sa[2]!==na&&(r.sa[2]=na,r.F.coneOuterGain=na)}p.hasOwnProperty("uid")&&(b.R.qa=p.uid)}else"number"===typeof A&&0!==A?(Q(b.R,!0),sb(b.R,A)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,m,n,x)}catch(Gb){console.error("[Construct] Audio: error starting playback: ",Gb);return}finally{c=g.join(" ");d=b.zb.get(c);if(!d)throw Error("expected pending tag");d.bd--;0===d.bd&&(d.resolve(),b.zb.delete(c))}t(b)}
async function tb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await ub(b,c);for(const h of R(b,c))if(!h.Pa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.s.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ha=d;h.Oa=g;h.Sd=a}S(b)}async function vb(b,a){const c=a.tags;a=a.rate;await ub(b,c);for(const d of R(b,c))d.ma!==a&&(d.ma=a,d.Ca())}async function wb(b,a){const c=a.tags;a=a.pos;await ub(b,c);for(const d of R(b,c))d.rc(a)}
async function xb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await qb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function yb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function zb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct] Audio: error loading convolution: ",m);return}for(const m of d){if("filter"===c)d=new self.be(b,...e);else if("delay"===c)d=new self.$d(b,...e);else if("convolution"===c){var g=d=new self.Zd(b,f.ja,...e),h=a.bufferType;g.wd=a.bufferOriginalUrl;g.xd=h}else if("flanger"===c)d=new self.ce(b,...e);else if("phaser"===
c)d=new self.ee(b,...e);else if("gain"===c)d=new self.de(b,...e);else if("stereopan"===c)d=new self.ge(b,...e);else if("tremolo"===c)d=new self.he(b,...e);else if("ringmod"===c)d=new self.fe(b,...e);else if("distortion"===c)d=new self.ae(b,...e);else if("compressor"===c)d=new self.Yd(b,...e);else if("analyser"===c)d=new self.Xd(b,...e);else throw Error("invalid effect type");g=b;h=m;h=h.toLowerCase();let n=g.la.get(h);n||(n=[],g.la.set(h,n));d.Gd=n.length;d.Wc=h;n.push(d);Ab(g,h)}Bb(b)}
async function Cb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.za()&&1===c||!e.za()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.la.values())for(const g of f)g.j();b.la.clear();b.fc=a.timeScale;b.Ic=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.va=a.isSilent;b.v.Ib(b.va);b.Wb=a.masterVolume;b.Na.gain.value=
b.Wb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>zb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Db(b,f,c)));S(b)}
async function Eb(b,a){try{const c=b.g.suspend(a.time);b.Fd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.gb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Hb(d)),b.Fd=!0);await c}catch(c){Hb(c)}}
function nb(b){b.Qb||(b.Lc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Qb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ka)if(g.bb()===c)return await Ib(g),g;if(f)return null;if(e&&(b.ac||b.Ed)){f=0;for(let h=0,m=b.ka.length;h<m;++h)g=b.ka[h],b.ka[f]=g,g.za()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Td;e&&f&&(b.Ed=!0);c=!e||b.ac||f?new self.ke(b,a,c,d,e,f):new self.ie(b,a,c,d,e);b.ka.push(c);await Ib(c);b.Ld.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Ld.add(a));return c}
function Jb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Kb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.ga()}function Ab(b,a){a=a.toLowerCase();let c=b.ga();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ga()):e.U(d[f+1].N())}}for(const f of Lb(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Fa&&b.Sc===a&&(b.Fa.disconnect(),b.Fa.connect(c))}
function*Lb(b,a){if(a)for(const c of b.H)Jb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Mb(b,a,c){return c?b.v.Re(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Nb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Jb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function qb(b,a,c,d,e,f){for(const g of b.H)if(g.bb()===c&&(g.kc()||f))return g.oa=e,g;a=await O(b,a,c,d,f);e="html5"===a.Dc?new self.je(a.s,a,e):new self.le(a.s,a,e);b.H.push(e);return e}
function pb(b,a){a=a.join(" ");let c=b.zb.get(a);if(!c){let d=null;c={bd:0,promise:new Promise(e=>d=e),resolve:d};b.zb.set(a,c)}c.bd++}function ub(b,a){return(b=b.zb.get((0===a.length?b.Jd:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Ma.size)t(b);else for(const a of b.H)if(!a.I&&!a.O()){t(b);break}}function Ob(b,a,c,d){k(b,"trigger",{type:a,tags:c,aiid:d})}function Bb(b){b.Oc||(b.Oc=!0,Promise.resolve().then(()=>Pb(b)))}
function Pb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.ab());k(b,"fxstate",{fxstate:a});b.Oc=!1}
async function Db(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,m=a.isLooping,n=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await qb(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],f=d.orient,b.Sa[0]=f[0],b.Sa[1]=f[1],b.Sa[2]=f[2],e.setPosition(...b.Ta),e.setOrientation(...b.Sa),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),sb(b,d));c.Play(m,n,p,0);a.isPlaying||c.fb();c.zc(a)}}}function Hb(b){console.error("[Audio] Offline rendering error: ",b)}
self.$a=class extends self.Fb{constructor(b){super(b,"audio");this.Na=this.g=null;this.Qb=this.Lc=!1;this.ya=()=>{if(!this.Lc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Qb&&(this.Lc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Qb=!1)}};this.ka=[];this.H=[];this.R=null;this.Jd=[];this.Ld=new Set;this.Kd=-1;this.zb=new Map;this.Wb=1;this.va=!1;this.Yc=0;this.fc=1;this.Ic=0;this.Nd="HRTF";this.yd="inverse";this.Od=600;this.Md=1E4;this.Qd=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Ed=this.ac=!1;this.Td=this.v.qe();this.la=new Map;this.Ma=new Set;this.Fd=this.Oc=!1;this.Sc="";this.Fa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Fa&&this.Fa.disconnect();this.Sc=c.toLowerCase();this.Fa=this.g.createMediaStreamSource(a);
this.Fa.connect(Kb(this,this.Sc))};this.Ob=null;self.C3Audio_GetOutputStream=()=>{this.Ob||(this.Ob=this.g.createMediaStreamDestination(),this.Na.connect(this.Ob));return this.Ob.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>mb(this,a)],["play",a=>ob(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Aa()}],["stop-all",()=>{for(const a of this.H)a.Aa()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.fb():d.Hb();S(this)}],["set-volume",
a=>{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>tb(this,a)],["set-master-volume",a=>{this.Wb=a.vol;this.Na.gain.value=this.Wb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Qb(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.v.Ib(this.va);for(const c of this.H)c.Lb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.sc(a)}],["set-playback-rate",a=>vb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),sb(d,a)}],["seek",a=>wb(this,a)],["preload",a=>xb(this,a)],["unload",a=>yb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.tc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>zb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.la.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Bb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.la.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.la.delete(a);Ab(this,a)}}],["tick",a=>{this.fc=a.timeScale;this.Ic=a.gameTime;this.Kd=a.tickCount;if(0!==this.Yc)for(var c of this.H)c.Ca();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&rb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Cb(this,a)],["offline-render-audio",a=>Eb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ga(){return this.Na}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ga()}Gb(){return this.va}Ba(b){this.v.Ba(b)}Ja(b){this.v.Ja(b)}Ka(){for(var b of this.Ma)b.Ka();
b=this.g.currentTime;for(var a of this.H)a.Ka(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.ab());k(this,"state",{tickCount:this.Kd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ma].map(c=>({tag:c.Wc,index:c.Gd,peak:c.Ua,rms:c.Pd,binCount:c.l.frequencyBinCount,freqBins:c.Dd}))});0===a.length&&0===this.Ma.size&&this.Rb&&(this.v.Pe(this.Ud),this.Rb=!1)}static ve(b){return b*lb}static hd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static te(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.hb.Db(self.$a);"use strict";function Ib(b){b.Ub||(b.Ub=b.yc());return b.Ub}self.dd=class{constructor(b,a,c,d,e){this.s=b;this.We=a;this.Ga=c;this.T=d;this.Te=e;this.Dc="";this.Ub=null}j(){this.Ub=this.s=null}yc(){}V(){return this.s.V()}nc(){return this.We}bb(){return this.Ga}mc(){return this.T}za(){return this.Te}ha(){}};"use strict";
self.ie=class extends self.dd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Dc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.tb=this.ub=null;this.M.addEventListener("canplaythrough",()=>!0);this.yb=this.V().createGain();this.wb=null;this.M.addEventListener("canplay",()=>{this.ub&&(this.ub(),this.tb=this.ub=null);!this.wb&&this.M&&(this.wb=this.V().createMediaElementSource(this.M),this.wb.connect(this.yb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ga}' error: `,f);this.tb&&(this.tb(f),this.tb=this.ub=null)})}j(){Nb(this.s,this);this.yb.disconnect();this.yb=null;this.wb.disconnect();this.wb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}yc(){return new Promise((b,a)=>{this.ub=b;this.tb=a;this.M.src=this.Ga})}W(){return this.M}ha(){return this.M.duration}};"use strict";
async function Rb(b){if(b.Da)return b.Da;var a=b.s.v;if("cordova"===a.A&&a.kd(b.Ga)&&a.Sb)b.Da=await a.Eb(b.Ga);else{a=await fetch(b.Ga);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Da=await a.arrayBuffer()}}async function Sb(b){if(b.ja)return b.ja;b.ja=await Mb(b.s,b.Da,b.Ve);b.Da=null}
self.ke=class extends self.dd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Dc="webaudio";this.ja=this.Da=null;this.Ve=!!f}j(){Nb(this.s,this);this.ja=this.Da=null;super.j()}async yc(){try{await Rb(this),await Sb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ga}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Tb=0;
function P(b,a){a=!!a;b.qb!==a&&(b.qb=a,b.qb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Nd,b.F.distanceModel=b.s.yd,b.F.refDistance=b.s.Od,b.F.maxDistance=b.s.Md,b.F.rolloffFactor=b.s.Qd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ga())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ga())))}
function Q(b,a){a=!!a;b.Tb!==a&&(b.Tb=a,b.Tb?(P(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.ga())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.ga())))}function sb(b,a){b.Tb&&b.Vc!==a&&(b.fa.pan.value=a,b.Vc=a)}function T(b,a){b.Ha=a;b.G.gain.cancelScheduledValues(0);b.Oa=-1;b.G.gain.value=b.oc()}function Qb(b,a){a=!!a;b.Pa!==a&&(b.Pa=a,b.Lb())}
function rb(b,a,c,d,e){if(b.qb){var f=b.Ta,g=b.Sa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Pc?b.s.Ic:performance.now()/1E3}
self.ed=class{constructor(b,a,c){this.s=b;this.P=a;this.oa=c;this.Mb=Tb++;this.G=this.V().createGain();this.G.connect(this.ga());this.F=null;this.qb=!1;this.Ta=[0,0,0];this.Sa=[0,0,0];this.sa=[0,0,0];this.fa=null;this.Tb=!1;this.Vc=0;this.I=!0;this.Y=this.ta=this.K=!1;this.Ha=1;this.Pa=!1;this.ma=1;b=this.s.Yc;this.Pc=1===b&&!this.za()||2===b;this.Oa=this.qa=-1;this.Sd=!1}j(){this.P=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}ga(){return Kb(this.s,0<this.oa.length?this.oa[0]:"")}nc(){return this.P.nc()}bb(){return this.P.bb()}mc(){return this.P.mc()}za(){return this.P.za()}O(){}kc(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}Ia(){}ha(){return this.P.ha()}Play(){}Aa(){}fb(){}Hb(){}Ka(b){-1!==this.Oa&&b>=this.Oa&&(this.Oa=-1,this.Sd&&this.Aa(),Ob(this.s,"fade-ended",this.oa,this.Mb))}oc(){const b=this.Ha;return isFinite(b)?b:0}Gb(){return this.s.Gb()}Lb(){}sc(){}Ca(){}rc(){}tc(){}pc(){}ab(){var b=
this.Mb,a=this.oa,c=this.ha(),d=-1===this.Oa?this.Ha:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ta,orient:this.Sa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ia(),playbackRate:this.ma,uid:this.qa,bufferOriginalUrl:this.nc(),bufferUrl:"",bufferType:this.mc(),isMusic:this.za(),isLooping:this.Y,isMuted:this.Pa,resumePosition:this.pc(),pan:f,stereoPan:this.fa?
this.Vc:null}}zc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ca());Qb(this,b.isMuted)}};"use strict";
self.je=class extends self.ed{constructor(b,a,c){super(b,a,c);this.P.yb.connect(this.G);this.P.onended=()=>this.Ac()}j(){this.Aa();this.P.yb.disconnect();super.j()}W(){return this.P.W()}Ac(){this.I=!0;this.qa=-1;Ob(this.s,"ended",this.oa,this.Mb)}O(){return this.W().ended}kc(){return this.I?!0:this.O()}Ia(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.bb()}' to position '${c}': `,e)}this.s.Ba(d);this.K=this.I=!1;this.Y=b;this.ma=1}Aa(){const b=this.W();b.paused||b.pause();this.s.Ja(b);this.I=!0;this.K=!1;this.qa=-1}fb(){if(!(this.K||this.I||this.O())){var b=this.W();b.paused||b.pause();this.s.Ja(b);this.K=!0}}Hb(){!this.K||this.I||this.O()||(this.s.Ba(this.W()),this.K=!1)}Lb(){this.W().muted=this.Pa||this.Gb()}sc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.W().loop=b)}Ca(){let b=this.ma;this.Pc&&(b*=this.s.fc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}rc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}pc(){return this.Ia()}tc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.s.Ba(this.W()),this.ta=!1)}};"use strict";
function V(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.jb=null}
self.le=class extends self.ed{constructor(b,a,c){super(b,a,c);this.o=null;this.Yb=d=>this.Ac(d);this.Kc=!0;this.jb=null;this.S=this.$b=this.bc=0;this.Tc=1}j(){this.Aa();V(this);this.Yb=null;super.j()}Ac(b){this.K||this.ta||b.target!==this.jb||(this.I=this.Kc=!0,this.qa=-1,V(this),Ob(this.s,"ended",this.oa,this.Mb))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Kc}kc(){return!this.o||this.I?!0:this.O()}Ia(){let b;b=this.K?this.S:this.$b+(U(this)-this.bc)*this.ma;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Tc=1;T(this,a);V(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.ja;this.o.connect(this.G);this.jb=this.o;this.o.onended=this.Yb;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Kc=!1;this.Y=b;this.ma=1;this.bc=U(this);this.$b=c}Aa(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.qa=-1}fb(){this.K||this.I||this.O()||(this.S=this.Ia(),this.Y&&(this.S%=this.ha()),this.K=!0,this.o.stop(0))}Hb(){!this.K||this.I||this.O()||(V(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.Yb,this.o.loop=this.Y,T(this,this.Ha),this.Ca(),this.o.start(0,this.S),this.bc=U(this),this.$b=this.S,this.K=!1)}oc(){return super.oc()*this.Tc}Lb(){this.Tc=this.Pa||this.Gb()?0:1;T(this,this.Ha)}sc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Ca(){let b=this.ma;this.Pc&&(b*=this.s.fc);this.o&&(this.o.playbackRate.value=b)}rc(b){this.I||this.O()||(this.K?this.S=b:(this.fb(),this.S=
b,this.Hb()))}pc(){return this.S}tc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.Ia(),this.Y&&(this.S%=this.ha()),this.o.stop(0)):this.ta=!1:this.ta&&(V(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.Yb,this.o.loop=this.Y,T(this,this.Ha),this.Ca(),this.o.start(0,this.S),this.bc=U(this),this.$b=this.S,this.ta=!1)}zc(b){super.zc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.s=b;this.g=b.V();this.Gd=-1;this.T=this.Wc="";this.m=null}j(){this.g=null}N(){}U(){}ab(){return{type:this.T,tag:this.Wc,params:this.m}}}
self.be=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.u=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i)}j(){this.u.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,X(this,this.D.gain,a,c,d)}}};
self.$d=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.u=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.vb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.nb=W(this);this.nb.gain.value=c;this.u.connect(this.vb);this.u.connect(this.h);this.vb.connect(this.i);this.vb.connect(this.X);this.X.connect(this.nb);this.nb.connect(this.vb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.vb.disconnect();
this.X.disconnect();this.nb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){const e=self.$a.hd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);X(this,this.nb.gain,e(a),c,d);break;case 5:this.m[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.Zd=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.xd=this.wd="";this.u=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.mb=this.g.createConvolver();this.mb.normalize=c;this.mb.buffer=a;this.u.connect(this.mb);this.u.connect(this.h);this.mb.connect(this.i)}j(){this.u.disconnect();this.mb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}ab(){const b=super.ab();b.bufferOriginalUrl=this.wd;b.bufferUrl="";b.bufferType=this.xd;return b}};
self.ce=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.u=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.pb=W(this);this.pb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=W(this);this.L.gain.value=c;this.u.connect(this.X);this.u.connect(this.h);this.X.connect(this.i);this.X.connect(this.pb);this.pb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.pb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;X(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,X(this,this.pb.gain,a/100,c,d)}}};
self.ee=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.u=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;X(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,X(this,this.B.frequency,a,c,d)}}};self.de=class extends Y{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.$a.hd;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.ge=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,c,d)}}};
self.he=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=W(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.fe=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.u=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Ab=W(this);this.Ab.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Ab.gain);this.B.start(0);this.u.connect(this.Ab);this.u.connect(this.h);this.Ab.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Ab.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.ae=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.u=W(this);this.dc=W(this);this.cc=W(this);b=d;.01>b&&(b=.01);this.dc.gain.value=b;this.cc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.hc=this.g.createWaveShaper();this.Ec=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ec[32768+e]=f,this.Ec[32768-
e-1]=-f;this.hc.curve=this.Ec;this.u.connect(this.dc);this.u.connect(this.h);this.dc.connect(this.hc);this.hc.connect(this.cc);this.cc.connect(this.i)}j(){this.u.disconnect();this.dc.disconnect();this.hc.disconnect();this.cc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.Yd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Xd=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Dd=new Float32Array(this.l.frequencyBinCount);this.Rd=new Uint8Array(a);this.Pd=this.Ua=0;b=this.s;b.Ma.add(this);S(b)}j(){this.s.Ma.delete(this);this.l.disconnect();super.j()}Ka(){this.l.getFloatFrequencyData(this.Dd);this.l.getByteTimeDomainData(this.Rd);const b=this.l.fftSize;let a=this.Ua=0;for(var c=0;c<b;++c){let d=(this.Rd[c]-
128)/128;0>d&&(d=-d);this.Ua<d&&(this.Ua=d);a+=d*d}c=self.$a.te;this.Ua=c(this.Ua);this.Pd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";function Z(b){b.stopPropagation()}function Ub(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.hb.Db(class extends self.ne{constructor(b){super(b);da(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}gd(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",
Z);c.addEventListener("keydown",Ub);c.addEventListener("keyup",Ub);c.addEventListener("click",e=>{e.stopPropagation();ea(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();ea(this,"dblclick",b)});c.addEventListener("input",()=>u(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.uc(c,a);return c}uc(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;b.spellcheck=a.spellCheck;
a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});
